services:

    akki.slimpay.form.type.gateway_configuration:
        class: Akki\SyliusPayumSlimpayPlugin\Form\Type\SlimpayGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: slimpay, label: akki.slimpay.gateway_label }
            - { name: form.type }

    akki.slimpay.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Payum\Slimpay\SlimpayGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: slimpay }